services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    ports:
      # - "9000:9000"  # client
      - "9001:9001"  # admin
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
