services:
  app:
    build: .

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # client
      - "9001:9001"  # admin
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
