name: build

on:
  push:
    branches:
      - master

env:
  GCP_PROJECT: newsagg-466216
  GCP_REGION: europe-central2
  REGISTRY: europe-central2-docker.pkg.dev
  IMAGE_NAME: newsagg
  IMAGE_TAG: latest

jobs:
  build:
    name: Build Docker Image and push to Artifact Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Build and tag
        env:
          IMAGE_URI: ${{ env.REGISTRY }}/${{ env.GCP_PROJECT }}/docker/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        run: |
          docker build . --platform=linux/amd64 \
            -t newsagg:latest \
            -t ${{ env.IMAGE_URI }}

      - name: Push to Artifact Registry
        env:
          IMAGE_URI: ${{ env.REGISTRY }}/${{ env.GCP_PROJECT }}/docker/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        run: |
          docker push ${{ env.IMAGE_URI }}
