name: cicd

on:
  push:
    branches:
      - master

env:
  GCP_PROJECT: newsagg-466216
  GCP_REGION: europe-central2
  REGISTRY: europe-central2-docker.pkg.dev
  IMAGE_NAME: newsagg
  IMAGE_TAG: latest
  SENTRY_DSN: "https://0a94989342892f02c23e3a6a3dc86939@o219112.ingest.us.sentry.io/4509685511225345"
  APP_SA: newsagg@newsagg-466216.iam.gserviceaccount.com

jobs:
  build:
    name: Build docker image and push to Artifact Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Build and tag
        env:
          IMAGE_URI: ${{ env.REGISTRY }}/${{ env.GCP_PROJECT }}/docker/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        run: |
          docker build . --platform=linux/amd64
            -t newsagg:latest
            -t ${{ env.IMAGE_URI }}

      - name: Push to Artifact Registry
        env:
          IMAGE_URI: ${{ env.REGISTRY }}/${{ env.GCP_PROJECT }}/docker/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        run: |
          docker push ${{ env.IMAGE_URI }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Generate .env.yaml
        run: |
          cat <<EOF > .env.yaml
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TARGET_CHANNEL: "@newnewsagg"

          BUCKET_ENDPOINT: storage.googleapis.com
          BUCKET_ACCESS_KEY: ${{ secrets.BUCKET_ACCESS_KEY }}
          BUCKET_SECRET_KEY: ${{ secrets.BUCKET_SECRET_KEY }}
          BUCKET_REGION: auto
          BUCKET_NAME: newsagg

          SENTRY_DSN: ${{ env.SENTRY_DSN }}
          EOF

      - name: "Deploy cloud run job"
        env:
          IMAGE_URI: ${{ env.REGISTRY }}/${{ env.GCP_PROJECT }}/docker/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        # TODO: fix job name
        run: |
          gcloud run jobs deploy newsagg-test
            --image=${{ env.IMAGE_URI }}
            --region=${{ env.GCP_REGION }}
            --memory=512Mi
            --max-retries=0
            --task-timeout=300s
            --env-vars-file=.env.yaml
            --parallelism 1
            --service-account ${{ env.APP_SA }}
